### PR TITLE
feat/PL 2385/improve release list ux

### PR DESCRIPTION
**Pull request by davidmdm**
image

### CODE REVIEW

**Review by riclima — APPROVED** [review]

**Review by alexstojda — COMMENTED** [review]
Could you add a legend after the list explaining the colours? :)

**Comment by davidmdm** [comment]
@alexstojda 
image

**Comment by alexstojda** [comment]
@davidmdm what do you think about calling it "reference-env"/"ref-env" instead of "main-env"?

**Comment by davidmdm** [comment]
@alexstojda for you, anything!

**Pull request merged**
